#!/opt/pwn.college/python
from flask import Flask

app = Flask(__name__)
with open("/flag", "r") as fObj:
    flag = fObj.read()

@app.route("/")
def hello():
	return flag

app.config["SERVER_NAME"] = f"challenge.localhost:80"
app.run("challenge.localhost", 80)

