#!/opt/pwn.college/python
import argparse
from pprint import pprint
from os.path import exists
from paceAITester.verify_helpers import extract_python_details, find_function_call

def main():
    if not exists(args.file):
        print(f"File {args.file} does not appear to exist.")
        exit(0)

    append = False
    start = False
    join = False

    lines = extract_python_details(args.file)
    for line in lines:
        if 'append' in line['function']:
            append = True
        elif 'start' in line['function']:
            start = True
        elif 'join' in line['function']:
            join = True

    if not join:
        print("You never joined your threads back to the main thread!")
        exit(0)
    if not append:
        print("Looks like you weren't using a list to track your threads! Try using a list!")
        exit(0)
    if not start:
        print("You never started your threads!")
        exit(0)

    with open('/flag', 'r') as fObj:
        print(fObj.read().strip())





if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("file", type=str, default='', help="User file to verify")
    args = parser.parse_args()
    main()
